name: Check with ReviewDog

on:
    workflow_dispatch:
    pull_request:
            branches:
                - to_merge

jobs:
    reviewdog:
        name: Setup ReviewDog
        runs-on: ubuntu-latest

        steps:
         - name: Checkout Repository
           uses: actions/checkout@v4

         - name: Setup ReviewDog
           uses: reviewdog/action-setup@v1
           with:
                reviewdog_version: latest
         - name: Setup node
           uses: actions/setup-node@v4
        
         - name: cache activate
           uses: actions/cache@v4
           id: node_modules_cache_id
           env:
            cache-name: '**/node_modeules'
           with:
            path: '**/node_modules'
            key: ${{ runner.os }}-lint-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
                ${{ runner.os }}-lint
        
         - name: Checking node_modules cache
           run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
        
         - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
           name: Install eslint and dependencies
           run: |
              npm ci
        
         - name: Installed eslint check
           run: npm ls --depth=1

    linterhtml:
          name: HTML Linter
          runs-on: ubuntu-latest
          needs: reviewdog
          steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: cache restore
              uses: actions/cache@v4
              with:
                restore-keys: |
                    ${{ runner.os }}-lint

            - name: Run html eslint with reviewdog
              uses: reviewdog/action-eslint@v1
              with:
                reporter: github-check
                eslint_flags: "./src/**/*.html"

    lintercss:
          name: CSS Linter
          runs-on: ubuntu-latest
          needs: reviewdog
          steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: cache restore
              uses: actions/cache@v4
              with:
                restore-keys: |
                    ${{ runner.os }}-lint

            - name: Run stylelint with reviewdog
              uses: reviewdog/action-stylelint@v1
              with:
                reporter: github-check
                eslint_flags: "./src/**/*.css"
